import { Database, MessageSquare, Users, Package, ClipboardList, Factory } from 'lucide-react';
import type { Product } from './products';

// Archived products - not currently shown in navigation but preserved for future use
export const archivedProducts: Product[] = [
  {
    id: 'unifyer',
    name: 'Unifyer',
    tagline: 'Unified Data Pipeline & Orchestration Engine',
    description: 'Powers enterprise data flows end-to-end with AI-assisted ingestion and transformation',
    outcome: 'Scalable, observable, resilient data foundation',
    icon: Database,
    heroDescription: 'Unifyer powers enterprise data flows end-to-end with multi-source data pipeline orchestration, AI-assisted ingestion & transformation, and AI-ready data modeling designed for modern decision systems. From rapid analytics platform setup to workflow automation, anomaly detection, and proactive pipeline monitoring, Unifyer gives teams a scalable, observable, and resilient data foundation for every AI use case.',
    keyBenefits: [
      'Multi-source data pipeline orchestration',
      'AI-assisted ingestion & transformation',
      'AI-ready data modeling for modern decision systems',
      'Rapid analytics platform setup',
      'Workflow automation and anomaly detection',
      'Proactive pipeline monitoring',
    ],
    features: [
      'Multi-source data integration',
      'AI-assisted pipeline creation',
      'Proactive monitoring & alerts',
      'Data quality management',
      'Anomaly detection',
      'Workflow automation',
    ],
    benefits: [
      'Faster data warehouse setup',
      'Reduced data engineering effort',
      'Reliable data quality',
      'AI-ready transformations',
      'Scalable data foundation',
    ],
    useCases: [
      'Enterprise data integration',
      'Cloud migration',
      'Data lake creation',
      'Real-time data streaming',
    ],
  },
  {
    id: 'aidr',
    name: 'AIDR',
    tagline: 'AI Data Reasoning & Analytics Suite',
    description: 'Turn organizational data into strategic answers with AI reasoning tools',
    outcome: 'Strategic answers from natural language',
    icon: MessageSquare,
    heroDescription: 'Turn organizational data into strategic answers with AIDR\'s suite of reasoning tools. Users can ask natural language questions across data sources, receive AI-generated insights & hypotheses, and automate routine analysis & reporting. With personalized and business-specific dashboards, deep NLP analytics, and scheduled workflows, AIDR supports both self-service analytics and structured decision rhythms across teams.',
    keyBenefits: [
      'Natural language questions across data sources',
      'AI-generated insights & hypotheses',
      'Automate routine analysis & reporting',
      'Personalized and business-specific dashboards',
      'Deep NLP analytics',
      'Scheduled workflows for structured decision rhythms',
    ],
    features: [
      'Natural language queries',
      'Instant dashboard creation',
      'Routine analysis automation',
      'Multi-source data access',
      'AI-generated insights',
      'Scheduled workflows',
    ],
    benefits: [
      'No SQL knowledge required',
      'Faster time to insights',
      'Reduced IT dependency',
      'Self-service analytics',
      'Structured decision rhythms',
    ],
    useCases: [
      'Ad-hoc business questions',
      'Quick report generation',
      'Data exploration',
      'Cross-department collaboration',
    ],
  },
  {
    id: 'sapro',
    name: 'SAPRO',
    tagline: 'Sales AI Productivity & Coaching Platform',
    description: 'Elevates sales effectiveness with performance tracking and AI-generated coaching',
    outcome: 'Actionable guidance that boosts productivity',
    icon: Users,
    heroDescription: 'SAPRO elevates sales effectiveness by combining performance tracking, contextual insights per rep, and AI-generated personalized coaching feedback that helps reps improve daily. With guided workflows, real-time customer & product intelligence, and sales incentive creation & ROI tracking, SAPRO turns raw performance data into actionable guidance that boosts productivity and drives results.',
    keyBenefits: [
      'Performance tracking with contextual insights per rep',
      'AI-generated personalized coaching feedback',
      'Guided workflows for daily improvement',
      'Real-time customer & product intelligence',
      'Sales incentive creation & ROI tracking',
      'Transform performance data into actionable guidance',
    ],
    features: [
      'Sales KPI tracking',
      'Performance analytics',
      'AI-powered coaching',
      'Incentive management',
      'Customer engagement workflows',
      'Real-time intelligence',
    ],
    benefits: [
      'Increased sales productivity',
      'Better-informed sales reps',
      'Personalized coaching at scale',
      'Optimized incentive ROI',
      'Drives measurable results',
    ],
    useCases: [
      'Sales performance management',
      'Rep coaching automation',
      'Customer follow-up workflows',
      'Incentive program tracking',
    ],
  },
  {
    id: 'aiven',
    name: 'AIVEN',
    tagline: 'AI Inventory & Vendor Management System',
    description: 'Brings precision to supply chain decision-making with AI-driven recommendations',
    outcome: 'Faster procurement cycles with reduced risk',
    icon: Package,
    heroDescription: 'AIVEN brings precision to supply chain decision-making with SKU and category-level tracking, AI-driven purchase order recommendations, and demand and lead-time forecasting. It includes multi-vendor RFQ management, risk detection for overstock or understock, and vendor performance analytics — all backed by workflow automation that speeds procurement cycles and reduces risk.',
    keyBenefits: [
      'SKU and category-level tracking',
      'AI-driven purchase order recommendations',
      'Demand and lead-time forecasting',
      'Multi-vendor RFQ management',
      'Risk detection for overstock or understock',
      'Vendor performance analytics',
      'Workflow automation for procurement',
    ],
    features: [
      'SKU-level inventory tracking',
      'Automated PO generation',
      'Vendor comparison & selection',
      'PO tracking & escalation',
      'Inventory assortment optimization',
      'Risk detection',
    ],
    benefits: [
      'Reduced stockouts',
      'Optimized inventory levels',
      'Better vendor management',
      'Automated purchasing workflows',
      'Faster procurement cycles',
    ],
    useCases: [
      'Retail inventory management',
      'Warehouse optimization',
      'Vendor relationship management',
      'Purchase order automation',
    ],
  },
  {
    id: '5on5',
    name: '5on5',
    tagline: 'Customer Experience AI Engine',
    description: 'Deliver personalized, context-aware customer experiences at scale',
    outcome: 'Every interaction more helpful and on brand',
    icon: MessageSquare,
    heroDescription: 'Deliver personalized, context-aware customer experiences at scale. 5on5 combines customized messaging for order and delivery status, AI-assisted support draft responses, and historical context integration to resolve queries faster. With next-best product recommendations, AI-generated engagement messaging, and automated communication workflows, 5on5 makes every interaction more helpful and on brand.',
    keyBenefits: [
      'Customized messaging for order and delivery status',
      'AI-assisted support draft responses',
      'Historical context integration to resolve queries faster',
      'Next-best product recommendations',
      'AI-generated engagement messaging',
      'Automated communication workflows',
    ],
    features: [
      'Personalized customer messaging',
      'AI-assisted response drafting',
      'Product recommendations',
      'Customer context management',
      'Automated workflows',
    ],
    benefits: [
      'Improved customer satisfaction',
      'Faster response times',
      'Increased upsell opportunities',
      'Consistent brand communication',
    ],
    useCases: [
      'Order status communications',
      'Customer query handling',
      'Personalized recommendations',
      'Customer engagement campaigns',
    ],
  },
  {
    id: 'voyager',
    name: 'Voyager',
    tagline: 'AI Project Execution Agent',
    description: 'Drive project success with continuous oversight from kickoff to close',
    outcome: 'Timely delivery with AI-assisted decision support',
    icon: ClipboardList,
    heroDescription: 'Drive project success with continuous oversight from kickoff to close. Voyager tracks project KPIs, budget and timelines, and uses continuous forecasting to flag risks early. With critical path detection, AI prioritization insights, automated escalations, and contractor/vendor automation, teams can focus on execution performance and timely delivery with the confidence of AI-assisted decision support.',
    keyBenefits: [
      'Track project KPIs, budget and timelines',
      'Continuous forecasting to flag risks early',
      'Critical path detection',
      'AI prioritization insights',
      'Automated escalations',
      'Contractor/vendor automation',
    ],
    features: [
      'Project metrics tracking',
      'Budget & timeline prediction',
      'AI-powered escalations',
      'Contractor engagement automation',
      'Critical path detection',
      'Risk flagging',
    ],
    benefits: [
      'Better project visibility',
      'Proactive delay management',
      'Improved accountability',
      'Automated stakeholder communication',
      'Timely delivery',
    ],
    useCases: [
      'Large-scale project management',
      'Construction project tracking',
      'Budget forecasting',
      'Contractor management',
    ],
  },
  {
    id: 'arios',
    name: 'Arios',
    tagline: 'AI Production Planning & Optimization Toolkit',
    description: 'Turns production complexity into clarity with AI-generated plans',
    outcome: 'Reduce variability and maximize efficiency',
    icon: Factory,
    heroDescription: 'Arios turns complexity into clarity with AI-generated daily and weekly production plans, constraint-based resource planning, and explainable AI reasoning for plan choices. Whether simulating scenarios, communicating plans broadly, tracking performance, or surfacing optimization opportunities, Arios empowers operations leaders to reduce variability, increase throughput, and maximize efficiency.',
    keyBenefits: [
      'AI-generated daily and weekly production plans',
      'Constraint-based resource planning',
      'Explainable AI reasoning for plan choices',
      'Scenario simulation',
      'Broad plan communication',
      'Performance tracking and optimization opportunities',
    ],
    features: [
      'AI-powered production planning',
      'Constraint-based scheduling',
      'Plan iteration through prompts',
      'Performance tracking & optimization',
      'Scenario simulation',
      'Explainable AI',
    ],
    benefits: [
      'Increased production efficiency',
      'Better resource utilization',
      'Data-driven planning decisions',
      'Continuous improvement insights',
      'Reduced variability',
    ],
    useCases: [
      'Construction planning',
      'Manufacturing scheduling',
      'Labour allocation',
      'Operations optimization',
    ],
  },
];
