import { Database, MessageSquare, Users, Package, ClipboardList, Factory } from 'lucide-react';
import type { Product } from './products';

// Archived products - not currently shown in navigation but preserved for future use
export const archivedProducts: Product[] = [
  {
    id: 'unifyer',
    name: 'Unifyer',
    tagline: 'Unified Data Pipeline & Orchestration Engine',
    description: 'Powers enterprise data flows end-to-end with AI-assisted ingestion and transformation',
    outcome: 'Scalable, observable, resilient data foundation',
    icon: Database,
    heroDescription: 'Unifyer powers enterprise data flows end-to-end with AI-assisted data ingestion & transformation, multi-source data pipeline orchestration, and AI-ready data modeling for agents & applications. With proactive pipeline monitoring & alerting, anomaly detection in data flows, workflow automation for data operations, and scalable architecture for enterprise data, Unifyer gives teams a resilient data foundation for every AI use case.',
    keyBenefits: [
      'AI-Assisted Data Ingestion & Transformation',
      'Multi-Source Data Pipeline Orchestration',
      'AI-Ready Data Modeling for Agents & Applications',
      'Proactive Pipeline Monitoring & Alerting',
      'Anomaly Detection in Data Flows',
      'Workflow Automation for Data Operations',
      'Scalable Architecture for Enterprise Data',
    ],
    features: [
      'AI-Assisted Data Ingestion & Transformation',
      'Multi-Source Data Pipeline Orchestration',
      'AI-Ready Data Modeling for Agents & Applications',
      'Proactive Pipeline Monitoring & Alerting',
      'Anomaly Detection in Data Flows',
      'Workflow Automation for Data Operations',
      'Scalable Architecture for Enterprise Data',
    ],
    benefits: [
      'Faster data warehouse setup',
      'Reduced data engineering effort',
      'Reliable data quality',
      'AI-ready transformations',
      'Scalable data foundation',
    ],
    useCases: [
      'Enterprise data integration',
      'Cloud migration',
      'Data lake creation',
      'Real-time data streaming',
    ],
  },
  {
    id: 'aidr',
    name: 'AIDR',
    tagline: 'AI Data Reasoning & Analytics Suite',
    description: 'Turn organizational data into strategic answers with AI reasoning tools',
    outcome: 'Strategic answers from natural language',
    icon: MessageSquare,
    heroDescription: 'Turn organizational data into strategic answers with AIDR\'s suite of reasoning tools. Users can ask natural language questions across all data sources, receive AI-generated insights & hypothesis testing, and automate routine analysis & reporting. With business-specific dashboard creation, personalized dashboards for teams & leaders, NLP-based deep-dive analytics, and scheduled analytics workflows, AIDR supports both self-service analytics and structured decision rhythms across teams.',
    keyBenefits: [
      'Natural Language Querying Across All Data Sources',
      'AI-Generated Insights & Hypothesis Testing',
      'Business-Specific Dashboard Creation',
      'Automated Routine Analysis & Reporting',
      'Personalized Dashboards for Teams & Leaders',
      'NLP-Based Deep-Dive Analytics',
      'Scheduled Analytics Workflows',
    ],
    features: [
      'Natural Language Querying Across All Data Sources',
      'AI-Generated Insights & Hypothesis Testing',
      'Business-Specific Dashboard Creation',
      'Automated Routine Analysis & Reporting',
      'Personalized Dashboards for Teams & Leaders',
      'NLP-Based Deep-Dive Analytics',
      'Scheduled Analytics Workflows',
    ],
    benefits: [
      'No SQL knowledge required',
      'Faster time to insights',
      'Reduced IT dependency',
      'Self-service analytics',
      'Structured decision rhythms',
    ],
    useCases: [
      'Ad-hoc business questions',
      'Quick report generation',
      'Data exploration',
      'Cross-department collaboration',
    ],
  },
  {
    id: 'sapro',
    name: 'SAPRO',
    tagline: 'Sales AI Productivity & Coaching Platform',
    description: 'Elevates sales effectiveness with performance tracking and AI-generated coaching',
    outcome: 'Actionable guidance that boosts productivity',
    icon: Users,
    heroDescription: 'SAPRO elevates sales effectiveness by combining KPI tracking & performance monitoring, contextual insights per sales representative, and AI-generated personalized coaching feedback. With sales incentive creation & ROI tracking, guided sales workflows & follow-ups, and productivity & engagement analytics, SAPRO turns raw performance data into actionable guidance that boosts productivity and drives results.',
    keyBenefits: [
      'KPI Tracking & Performance Monitoring',
      'Contextual Insights per Sales Representative',
      'AI-Generated Personalized Coaching Feedback',
      'Sales Incentive Creation & ROI Tracking',
      'Guided Sales Workflows & Follow-Ups',
      'Productivity & Engagement Analytics',
    ],
    features: [
      'KPI Tracking & Performance Monitoring',
      'Contextual Insights per Sales Representative',
      'AI-Generated Personalized Coaching Feedback',
      'Sales Incentive Creation & ROI Tracking',
      'Guided Sales Workflows & Follow-Ups',
      'Productivity & Engagement Analytics',
    ],
    benefits: [
      'Increased sales productivity',
      'Better-informed sales reps',
      'Personalized coaching at scale',
      'Optimized incentive ROI',
      'Drives measurable results',
    ],
    useCases: [
      'Sales performance management',
      'Rep coaching automation',
      'Customer follow-up workflows',
      'Incentive program tracking',
    ],
  },
  {
    id: 'aiven',
    name: 'AIVEN',
    tagline: 'AI Inventory & Vendor Management System',
    description: 'Brings precision to supply chain decision-making with AI-driven recommendations',
    outcome: 'Faster procurement cycles with reduced risk',
    icon: Package,
    heroDescription: 'AIVEN brings precision to supply chain decision-making with SKU & category-level inventory tracking, AI-driven purchase order recommendations, and demand, sales plan & lead-time forecasting. It includes multi-vendor RFQ management & comparison, PO tracking, alerts & escalations, overstock & understock risk detection, vendor performance analytics & reporting, inventory assortment recommendations, and workflow automation for buying & procurement teams.',
    keyBenefits: [
      'SKU & Category-Level Inventory Tracking',
      'AI-Driven Purchase Order Recommendations',
      'Demand, Sales Plan & Lead-Time Forecasting',
      'Multi-Vendor RFQ Management & Comparison',
      'PO Tracking, Alerts & Escalations',
      'Overstock & Understock Risk Detection',
      'Vendor Performance Analytics & Reporting',
      'Inventory Assortment Recommendations',
      'Workflow Automation for Buying & Procurement Teams',
    ],
    features: [
      'SKU & Category-Level Inventory Tracking',
      'AI-Driven Purchase Order Recommendations',
      'Demand, Sales Plan & Lead-Time Forecasting',
      'Multi-Vendor RFQ Management & Comparison',
      'PO Tracking, Alerts & Escalations',
      'Overstock & Understock Risk Detection',
      'Vendor Performance Analytics & Reporting',
      'Inventory Assortment Recommendations',
      'Workflow Automation for Buying & Procurement Teams',
    ],
    benefits: [
      'Reduced stockouts',
      'Optimized inventory levels',
      'Better vendor management',
      'Automated purchasing workflows',
      'Faster procurement cycles',
    ],
    useCases: [
      'Retail inventory management',
      'Warehouse optimization',
      'Vendor relationship management',
      'Purchase order automation',
    ],
  },
  {
    id: '5on5',
    name: '5on5',
    tagline: 'Customer Experience AI Engine',
    description: 'Deliver personalized, context-aware customer experiences at scale',
    outcome: 'Every interaction more helpful and on brand',
    icon: MessageSquare,
    heroDescription: 'Deliver personalized, context-aware customer experiences at scale. 5on5 combines personalized order & delivery status messaging, AI-assisted customer support response drafting, and context-aware query resolution. With historical communication & data context integration, next-best product recommendation, AI-generated customer engagement messaging, sales & upsell enablement for reps, automated customer communication workflows, and real-time customer & product intelligence, 5on5 makes every interaction more helpful and on brand.',
    keyBenefits: [
      'Personalized Order & Delivery Status Messaging',
      'AI-Assisted Customer Support Response Drafting',
      'Context-Aware Query Resolution',
      'Historical Communication & Data Context Integration',
      'Next-Best Product Recommendation',
      'AI-Generated Customer Engagement Messaging',
      'Sales & Upsell Enablement for Reps',
      'Automated Customer Communication Workflows',
      'Real-Time Customer & Product Intelligence',
    ],
    features: [
      'Personalized Order & Delivery Status Messaging',
      'AI-Assisted Customer Support Response Drafting',
      'Context-Aware Query Resolution',
      'Historical Communication & Data Context Integration',
      'Next-Best Product Recommendation',
      'AI-Generated Customer Engagement Messaging',
      'Sales & Upsell Enablement for Reps',
      'Automated Customer Communication Workflows',
      'Real-Time Customer & Product Intelligence',
    ],
    benefits: [
      'Improved customer satisfaction',
      'Faster response times',
      'Increased upsell opportunities',
      'Consistent brand communication',
    ],
    useCases: [
      'Order status communications',
      'Customer query handling',
      'Personalized recommendations',
      'Customer engagement campaigns',
    ],
  },
  {
    id: 'tars',
    name: 'TARS',
    tagline: 'AI Project Execution Agent',
    description: 'Drive project success with continuous oversight from kickoff to close',
    outcome: 'Timely delivery with AI-assisted decision support',
    icon: ClipboardList,
    heroDescription: 'Drive project success with continuous oversight from kickoff to close. TARS provides project KPI & accountability tracking, budget & timeline monitoring, and continuous forecasting of cost & schedule. With critical path & risk identification, AI-driven insights for prioritization, automated escalations for delays, contractor & vendor engagement automation, and execution performance dashboards, teams can focus on execution and timely delivery with the confidence of AI-assisted decision support.',
    keyBenefits: [
      'Project KPI & Accountability Tracking',
      'Budget & Timeline Monitoring',
      'Continuous Forecasting of Cost & Schedule',
      'Critical Path & Risk Identification',
      'AI-Driven Insights for Prioritization',
      'Automated Escalations for Delays',
      'Contractor & Vendor Engagement Automation',
      'Execution Performance Dashboards',
    ],
    features: [
      'Project KPI & Accountability Tracking',
      'Budget & Timeline Monitoring',
      'Continuous Forecasting of Cost & Schedule',
      'Critical Path & Risk Identification',
      'AI-Driven Insights for Prioritization',
      'Automated Escalations for Delays',
      'Contractor & Vendor Engagement Automation',
      'Execution Performance Dashboards',
    ],
    benefits: [
      'Better project visibility',
      'Proactive delay management',
      'Improved accountability',
      'Automated stakeholder communication',
      'Timely delivery',
    ],
    useCases: [
      'Large-scale project management',
      'Construction project tracking',
      'Budget forecasting',
      'Contractor management',
    ],
  },
  {
    id: 'arios',
    name: 'Arios',
    tagline: 'AI Production Planning & Optimization Toolkit',
    description: 'Turns production complexity into clarity with AI-generated plans',
    outcome: 'Reduce variability and maximize efficiency',
    icon: Factory,
    heroDescription: 'Arios turns complexity into clarity with AI-generated daily & weekly production plans, constraint-based planning (work pending, POs, resources), and explainable AI reasoning for plans. With scenario simulation & iterative planning via prompts, plan finalization & organization-wide communication, performance tracking against plan, productivity & efficiency analytics, and AI-suggested optimization opportunities, Arios empowers operations leaders to reduce variability, increase throughput, and maximize efficiency.',
    keyBenefits: [
      'AI-Generated Daily & Weekly Production Plans',
      'Constraint-Based Planning (Work Pending, POs, Resources)',
      'Explainable AI Reasoning for Plans',
      'Scenario Simulation & Iterative Planning via Prompts',
      'Plan Finalization & Organization-Wide Communication',
      'Performance Tracking Against Plan',
      'Productivity & Efficiency Analytics',
      'AI-Suggested Optimization Opportunities',
    ],
    features: [
      'AI-Generated Daily & Weekly Production Plans',
      'Constraint-Based Planning (Work Pending, POs, Resources)',
      'Explainable AI Reasoning for Plans',
      'Scenario Simulation & Iterative Planning via Prompts',
      'Plan Finalization & Organization-Wide Communication',
      'Performance Tracking Against Plan',
      'Productivity & Efficiency Analytics',
      'AI-Suggested Optimization Opportunities',
      'Planning / Scheduling / Scenarios',
    ],
    benefits: [
      'Increased production efficiency',
      'Better resource utilization',
      'Data-driven planning decisions',
      'Continuous improvement insights',
      'Reduced variability',
    ],
    useCases: [
      'Construction planning',
      'Manufacturing scheduling',
      'Labour allocation',
      'Operations optimization',
    ],
  },
];
